---
- name: Setup Java 21 and JMeter on Amazon Linux
  hosts: docker # Replace with your target host group
  become: yes

  vars:
    docker_image_name: 'nginx' # Change this to your desired image (e.g., 'ubuntu', 'myrepo/myapp:latest')
    docker_image_tag: 'latest'

- name: 3. Pull the Docker Image
  community.docker.docker_image:
     name: "{{ docker_image_name }}"
     tag: "{{ docker_image_tag }}"
     source: pull # Explicitly pull the image
     state: present
     register: image_pull_result
  
- name: Enable docker.service
  systemd:
       name: docker.service
       daemon_reload: true
       enabled: true

- name: Ensure Docker service is running and enabled at boot
  ansible.builtin.service:
       name: docker
       state: started
       enabled: yes



