---
- name: Setup Java 21 and JMeter on Amazon Linux
  hosts: jmeter # Replace with your target host group
  become: yes
  vars:
    jmeter_version: 5.6.3 # Check Apache JMeter website for the latest version
    jmeter_download_url: "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-{{ jmeter_version }}.tgz"
    install_dir: /opt

  tasks:
    - name: 1. Update all installed packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Amazon'

  - name: Import Corretto public key
      ansible.builtin.shell: |
        wget -O - https://apt.corretto.aws/corretto.key | sudo gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg
      args:
        creates: /usr/share/keyrings/corretto-keyring.gpg

    - name: Add Corretto repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/corretto.list
        line: "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main"
        create: yes
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Amazon Corretto 21 JDK
      ansible.builtin.apt:
        name: java-21-amazon-corretto-jdk
        state: present



    - name: 3. Download Apache JMeter archive
      ansible.builtin.get_url:
        url: "{{ jmeter_download_url }}"
        dest: "/tmp/apache-jmeter-{{ jmeter_version }}.tgz"
        checksum: "sha512:{{ jmeter_download_url }}.sha512" # Optional, but recommended for security
        mode: '0644'

    - name: 4. Unarchive JMeter to installation directory
      ansible.builtin.unarchive:
        src: "/tmp/apache-jmeter-{{ jmeter_version }}.tgz"
        dest: "{{ install_dir }}"
        remote_src: yes

    - name: 5. Create a symbolic link for easier access
      ansible.builtin.file:
        src: "{{ install_dir }}/apache-jmeter-{{ jmeter_version }}"
        dest: "{{ install_dir }}/jmeter-latest"
        state: link
