---
- name: Install and Configure NGINX on Red Hat/CentOS EC2
  hosts: nginxservers 
  become: true  # Use sudo/become for root privileges

  tasks:





    - name: Install NGINX package
      ansible.builtin.yum:
        name: nginx
        state: latest
      notify:
        - Reload NGINX

    - name: Ensure NGINX service is started and enabled at boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      notify:
        - Reload NGINX

    - name: Copy custom index.html file to NGINX web root
      ansible.builtin.copy:
        src: files/index.html
        # Standard web root for NGINX installed via yum/dnf on Red Hat-based systems
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
      notify:
        - Reload NGINX

    - name: 5. Ensure firewalld service is running
      ansible.builtin.systemd_service:
        name: firewalld
        state: started
        enabled: yes

    - name: 6. Open HTTP (port 80) permanently in firewalld
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes  # Reloads firewalld immediately



        
  handlers:
    - name: Reload NGINX
      ansible.builtin.service:
        name: nginx
        state: reloaded



