---
- name: Install Nginx using privilege escalation
  hosts: web_servers
  become: true             # 👈 Enables privilege escalation for the entire play
  become_method: sudo      # 👈 Specifies the method (sudo is default)
  become_user: root        # 👈 Specifies the user to become (root is default)
  
  tasks:
    - name: Ensure Nginx package is installed (requires root)
      ansible.builtin.package:
        name: nginx
        state: present
    
    - name: Ensure Nginx service is running (requires root)
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Create a file as the current user (overrides become)
      ansible.builtin.file:
        path: /tmp/nginx_installed.txt
        state: touch
        owner: '{{ ansible_user }}' # Assuming ansible_user is defined in inventory
        mode: '0644'
      become: false          # 👈 Explicitly disables privilege escalation for this task
