---
- name: Deploy and Configure NGINX on RHEL 9 (EC2)
  hosts: my_target_host 
  become: yes    
  
  tasks:
    - name: 1. Install NGINX package using DNF
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: 2. Enable and Start the NGINX service
      ansible.builtin.systemd_service:
        name: nginx
        state: started     # Equivalent to 'systemctl start nginx'
        enabled: yes       # Equivalent to 'systemctl enable nginx'
