---
- name: Execute a local script on the Ansible Control Machine
  hosts: localhost         # Target the local machine
  connection: local        # Use a local connection type
  gather_facts: no         # No need to gather facts for this simple task
  become: true
  tasks:

    - name: Run the script using the 'script' module
      script: ./generate_ssh_config.py
      delegate_to: localhost
      become: true  #  This enables 'sudo' on the control no
      register: script_output

    - name: Display the script's output
      debug:
        msg: "{{ script_output.stdout_lines }}"


    - name: Find a process ID using shell features
      ansible.builtin.shell: "cat /tmp/inventory"
      register: nginx_pid_line

    - name: Debug PID line
      ansible.builtin.debug:
      var: nginx_pid_line.stdout
