---
- name: Execute a local script on the Ansible Control Machine
  hosts: localhost         # Target the local machine
  connection: local        # Use a local connection type
  gather_facts: no         # No need to gather facts for this simple task

  tasks:
    - name: Ensure the script is executable (best practice)
      # but it's often used when running a local task against remote hosts.
      delegate_to: localhost

    - name: Run the script using the 'script' module
      script: ./generate_ssh_config.py
      register: script_output

    - name: Display the script's output
      debug:
        msg: "{{ script_output.stdout_lines }}"

    - name: Dynamically append files using template
      ansible.builtin.shell: 'cat /tmp/config_tmp >> bastion1_part'  
 
    - name: Rename bastion1_part to config 
      ansible.builtin.shell: 'mv bastion1_part config'  
    

   - name: Copy config file to jenkins
     ansible.builtin.copy:
       src: config 
       dest: /var/lib/jenkins/.ssh/config              
       owner: jenkins
       mode: '0755'

   - name: Copy config file to ec2-user 
     ansible.builtin.copy:
       src: config 
       dest: /home/ec2-user/.ssh/config              
       owner: ec2-user 
       mode: '0755'

   - name: Copy inventory 
     ansible.builtin.copy:
       src: /tmp/inventory 
       dest: /etc/ansible/inventory.ini              
       owner: root 
       mode: '0755'

